### ISSUE TITLE
Connection Settings

### ISSUE THREAD

**Issue by robblot** [shivam01990/InventoryManagement#1]
Hello,
    When I input the data to configure the connection settings I keep getting a Fails message. Is there a format I need to follow?

Input parameters:
Server:        ROBBLOT-PC\SQLEXPRESS
Database:    inventory
User:            robblot
Password:    GAUIX3

**Comment by shivam01990** [comment]
Hello ,

Please make sure that Database is configured correctly & add one entry of user in user table.
Please check your sql connection again . I hope its working.
Other wise i can help you by team weaver.

please check screen cast: http://screencast.com/t/Oo2N8tQkjL

**Comment by robblot** [comment]
Working now. Very nice app

**Comment by shivam01990** [comment]
Thanks!!!!!!!!!!!!!

You need any help then ask. I created this app to learn WPF .

**Comment by robblot** [comment]
I am trying to learn WPF also and MVVM.

Thank You,

Robert Blot

 mailto:robblot@gmail.com robblot@gmail.com

(859) 382-0237
